<?php
/**
 * VooDoo Music Box
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.voodoomusicbox.com/license/new-bsd
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@voodoomusicbox.com so we can send you a copy immediately.
 *
 * @category   VooDoo Music Box
 * @package    Admin
 * @subpackage View
 * @copyright  Copyright (c) 2005-2009 VooDoo Music Box. (http://www.VoodooMusicBox.com)
 * @license    http://www.VoodooMusicBox.com/license/new-bsd     New BSD License
 * @version    $Id: index.phtml 4 2009-6-1 Jaimie $
 */
?>
<div class="grid_16">                
    <div class="box">
        <h2><?= $this->translate('Head_Statistics'); ?></h2>
        <div class="block">
            <div class="grid_3"><b><?= $this->translate('Text_Admin_Artist_Count'); ?>:</b></div>
            <div class="grid_13"><?= $this->artistCount; ?></div> 
            <div class="clear"></div>
    
            <div class="grid_3"><b><?= $this->translate('Text_Admin_Album_Count'); ?>:</b></div>
            <div class="grid_13"><?= $this->albumCount; ?></div> 
            <div class="clear"></div>

            <div class="grid_3"><b><?= $this->translate('Text_Admin_File_Count'); ?>:</b></div>
            <div class="grid_13"><?= $this->fileCount; ?></div> 
            <div class="clear"></div>

            <div class="grid_3"><b><?= $this->translate('Text_Admin_Account_Count'); ?>:</b></div>
            <div class="grid_13"><?= $this->accountCount; ?></div> 
            <div class="clear"></div>

            
        </div>
    </div>
</div>
