<?php
/**
 * VooDoo Music Box
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.voodoomusicbox.com/license/new-bsd
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@voodoomusicbox.com so we can send you a copy immediately.
 *
 * @category   VooDoo Music Box
 * @package    Admin
 * @subpackage View
 * @copyright  Copyright (c) 2005-2009 VooDoo Music Box. (http://www.VoodooMusicBox.com)
 * @license    http://www.VoodooMusicBox.com/license/new-bsd     New BSD License
 * @version    $Id: add-help-en.phtml 4 2009-6-1 Jaimie $
 */
?>
<div class="box">
        <h2>Help</h2>
        <div class="block" id="help">
            <h5>Page Name</h5>
            <p align="justify">
                The page name will give your page a name so that the system will recognize the page. <i>Page Names</i> are also used for search engine
                friendly links to your page. Use <i>Page Names</i> that describe your page and relate to the text contained in the page. For example
                if your page is about your company name the page <i>about vcat</i>. The system will build a <i>Page Name</i> about-vcat.html
            </p>

            <h5>Add To Menu</h5>
            <p align="justify">
                Checking the <i>Add To Menu</i> will add a link to the main <i>Pages Menu Box</i> that shows up in the menu. If the <i>Pages Menu Box</i>
                is disabled in the configuration checking this box will have no effect.
                
            </p>
            
            <h5>Require Account</h5>
            <p align="justify">Checking the <i>Require Account</i> will validate that the reader is signed into their account and the account 
                is active. This allows you to create protected content and pages.
            </p>

            <h5>Page Layout<h5>
            <p align="justify">


            </p>

        </div>
    </div>
