<?php
/**
 * VooDoo Music Box
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.voodoomusicbox.com/license/new-bsd
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@voodoomusicbox.com so we can send you a copy immediately.
 *
 * @category   VooDoo Music Box
 * @package    Admin
 * @subpackage View
 * @copyright  Copyright (c) 2005-2009 VooDoo Music Box. (http://www.VoodooMusicBox.com)
 * @license    http://www.VoodooMusicBox.com/license/new-bsd     New BSD License
 * @version    $Id: search-box.phtml 4 2009-6-1 Jaimie $
 */
?>
<div class="box">
    <h2><?= $this->translate('Box_Head_Account_Search');?></h2>
    <div class="block" >
        <form method="post" action="admin/account/search">
            <fieldset>
                <p align="center"><?= $this->translate('Text_Account_Keyword_Search');?></p>
                <p align="center"><input type="text" name="keyword" id="keyword" value=""></p>
                <p align="center"><input type="submit" name="search" id="search" value="<?= $this->Translate('Form_Account_Button_Search'); ?>"></p>
            </fieldset>
        </form>
    </div>
</div>
