<?php
/**
 * VooDoo Music Box
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.voodoomusicbox.com/license/new-bsd
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@voodoomusicbox.com so we can send you a copy immediately.
 *
 * @category   VooDoo Music Box
 * @package    Default
 * @subpackage View
 * @copyright  Copyright (c) 2005-2009 VooDoo Music Box. (http://www.VoodooMusicBox.com)
 * @license    http://www.VoodooMusicBox.com/license/new-bsd     New BSD License
 * @version    $Id: account.phtml 4 2009-6-1 Jaimie $
 */
?>
<div class="grid_4">
    <div class="box">
        <h2><?= $this->translate('Menu_Account'); ?></h2>
        <div class="block" id="list-items">
            <ul class="menu">
                <li><a href="account/"><?= $this->translate('Menu_Account'); ?></a></li>
                <li><a href="account/edit"><?= $this->translate('Menu_Account_Edit'); ?></a></li>
                <li><a href="account/address"><?= $this->translate('Menu_Account_Address'); ?></a></li>
                <li><a href="account/password"><?= $this->translate('Menu_Account_Password');?></a></li>
                <li><a href="account/email"><?= $this->translate('Menu_Account_Email');?></a></li>               
            </ul>
        </div>
    </div>
</div>
