<?php
/**
 * VooDoo Music Box
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.voodoomusicbox.com/license/new-bsd
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@voodoomusicbox.com so we can send you a copy immediately.
 *
 * @category   VooDoo Music Box
 * @package    Core
 * @subpackage View
 * @copyright  Copyright (c) 2005-2009 VooDoo Music Box. (http://www.VoodooMusicBox.com)
 * @license    http://www.VoodooMusicBox.com/license/new-bsd     New BSD License
 * @version    $Id: main.phtml 4 2009-6-1 Jaimie $
 */
?>

<?= $this->render('header.phtml'); ?>

<div class="grid_16">
    <!-- Left Column -->
    <div class="grid_4">
        <?= $this->action('left', 'box'); ?>
        <br>
    </div>
    <!-- EOF Left Column -->

    <!-- Main Column -->
    <div class="grid_12">
        <?= $this->layout()->content; ?>
    </div>
    <!-- EOF Main Column -->
</div>
   
<div class="clear"></div>

<?= $this->render('footer.phtml');  ?>
    
