<?php
/**
 * VooDoo Music Box
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.voodoomusicbox.com/license/new-bsd
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@voodoomusicbox.com so we can send you a copy immediately.
 *
 * @category   VooDoo Music Box
 * @package    Admin
 * @subpackage View
 * @copyright  Copyright (c) 2005-2009 VooDoo Music Box. (http://www.VoodooMusicBox.com)
 * @license    http://www.VoodooMusicBox.com/license/new-bsd     New BSD License
 * @version    $Id: update.phtml 4 2009-6-1 Jaimie $
 */
?>
<div class="grid_4">
    <?= $this->partial('country/menu.phtml'); ?>
</div>
<div class="grid_12">
    <div class="box">
        <h2><?= $this->translate('Box_Head_Conuntry_Update');?></h2>
        <div class="block">

            
                <fieldset>
                    <legend><?= $this->translate('Form_Legend_Country_Update'); ?></legened>
                    <p><?= $this->translate('Text_Country_Confirm_Update'); ?></p>
                    <?= $this->form; ?>
                </fieldset>
           

         </div>
    </div>
</div>
