<?php
/**
 * VooDoo Music Box
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.voodoomusicbox.com/license/new-bsd
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@voodoomusicbox.com so we can send you a copy immediately.
 *
 * @category   VooDoo Music Box
 * @package    Box
 * @subpackage View
 * @copyright  Copyright (c) 2005-2009 VooDoo Music Box. (http://www.VoodooMusicBox.com)
 * @license    http://www.VoodooMusicBox.com/license/new-bsd     New BSD License
 * @version    $Id: top-played.phtml 4 2009-6-1 Jaimie $
 */
?>
<div class="grid_4">
    <div class="box">
        <h2><?= $this->translate('Box_Head_Top_Played'); ?></h2>
        <div class="block">
            <ul class="menu">      
            <? if ($this->topPlayed): ?>
                <? foreach($this->topPlayed as $played): ?>
                    <li> <a href="artist/view/<?= urlencode($played['artist']); ?>/<?= urlencode($played['album']); ?>/<?= urlencode($played['title']); ?>" " id="<?= $played['file_id']; ?>"> <?= $played['title']; ?></a>
                         <div dojoType="dijit.Tooltip" connectId="<?= $played['file_id']; ?>" label="<h6><?= $played['title']; ?></h6><b>Artist:</b> <?=$played['artist']; ?><br><b>Album:</b> <?= $played['album']?><br><b>Plays:</b> <?= $played['play_count']; ?> "></div>
                    </li>
                <? endforeach; ?>
            <? endif; ?>
            </ul>
        </div>
    </div>
</div>
