<?php
/**
 * VooDoo Music Box
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.voodoomusicbox.com/license/new-bsd
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@voodoomusicbox.com so we can send you a copy immediately.
 *
 * @category   VooDoo Music Box
 * @package    Default
 * @subpackage View
 * @copyright  Copyright (c) 2005-2009 VooDoo Music Box. (http://www.VoodooMusicBox.com)
 * @license    http://www.VoodooMusicBox.com/license/new-bsd     New BSD License
 * @version    $Id: album-not-found.phtml 4 2009-6-1 Jaimie $
 */
?>
<?= $this->action('top-played', 'box'); ?>

<div class="grid_12">
    <div class="box">
        <h2><?= $this->translate('Box_Head_Error_Album_Not_Found'); ?></h2>
        <div class="block">
           <p><?= $this->translate('Txt_Error_Album_Not_Found'); ?> <b><?= $this->album; ?></b>. <br><br>
            <a href="artist/view/<?= urlencode($this->artist); ?>" title="<?= $this->translate('Link_Back_To_Artist'); ?>"><?= $this->translate('Link_Back_To_Artist'); ?></a></p>

        </div>    
    </div>
</div>
