<?php
/**
 * VooDoo Music Box
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.voodoomusicbox.com/license/new-bsd
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@voodoomusicbox.com so we can send you a copy immediately.
 *
 * @category   VooDoo Music Box
 * @package    Admin
 * @subpackage View
 * @copyright  Copyright (c) 2005-2009 VooDoo Music Box. (http://www.VoodooMusicBox.com)
 * @license    http://www.VoodooMusicBox.com/license/new-bsd     New BSD License
 * @version    $Id: index.phtml 4 2009-6-1 Jaimie $
 */
?>
<div class="grid_16">                
    <div class="box">
        <h2><?= $this->translate('Box_Head_Import'); ?></h2>
            <br>
            <p><?= $this->translate('Text_Import_Warning'); ?></p>

            <? if ($this->iframe): ?>
            
                <iframe src="admin/import/process/directory/<?= $this->directory; ?>" width="100%" height="400"   ></iframe>
            <? else: ?>
                <fieldset>
                <div class="grid_16"><center><?= $this->letterSearch; ?></center></div>
                
                <div class="clear"></div>

                <div class="grid_1"><br></div>
                <div class="grid_3"><strong><?= $this->translate('Field_Import_Dir_Name'); ?></strong></div>
                <div class="grid_9"><strong><?= $this->translate('Field_Import_Dir_Path'); ?></strong></div>
                <div class="grid_2"><strong><?= $this->translate('Field_Import_Dir_Last_Scan'); ?></strong></div>
                <div class="clear"></div>
                <hr>
                <?= $this->form; ?>
                <center><?= $this->paginationControl($this->folderArray, 'Sliding', 'pagination_control.phtml'); ?></center>
                </fieldset>
            <? endif; ?>

    </div>
</div>
